version: '3'
services:
  postgres:
    image: postgres:11
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: nodemon ./server/server.js