version: '3'

networks:
  hvs-net:
    driver: bridge

services:
  postgres:
    image: postgres:11
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - hvs-net
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: nodemon ./server/server.js
    networks: 
      - hvs-net
    ports:
      - "80:3000"
    links:
      - postgres