version: '3.2'

services:
  app:
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=database
      - POSTGRES_DB=my_db
      - POSTGRES_PORT=5432
    command: ["node", "./server.js"]