version: '3.2'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=database
      - POSTGRES_DB=my_db
      - POSTGRES_PORT=5432
    ports:
      - "3000:3000"
    command: ["node", "./server.js"]