version: '3.2'

networks: 
  database:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=database
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"
    networks:
      - database
  app:
    environment:
      - NODE_ENV=development
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=database
      - POSTGRES_DB=my_db
      - POSTGRES_PORT=5432
    depends_on: 
      - postgres
    networks: 
      - database
    command: ["nodemon", "./server.js"]