version: '3.2'

networks: 
  database:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hvs
      - POSTGRES_USER=hvs
      - POSTGRES_DB=hvs
    ports:
      - "5432:5432"
    networks:
      - database
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - POSTGRES_PASSWORD=hvs
      - POSTGRES_USER=hvs
      - POSTGRES_DB=hvs
    ports:
      - "80:3000"
    depends_on: 
      - postgres
    networks: 
      - database
    command: ["nodemon", "./server/server.js"]