version: '3'
services:
  postgres:
    image: postgres:11
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    container_name: server
    build: ./server
    ports:
      - "80:3000"
    volumes:
      - .:/server
    links:
      - postgres